$ErrorActionPreference = "Stop"

# Ensure script executes from repository root
$RepoRoot = (Get-Item $PSScriptRoot).Parent.FullName
if (!(Test-Path "$RepoRoot\go.mod")) {
    Write-Host "INFRASTRUCTURE ERROR: Script must be run from within the Aether repository." -ForegroundColor Red
    exit 1
}
Set-Location $RepoRoot

Write-Host "=============================================" -ForegroundColor Cyan
Write-Host " AETHER CLEAN-DIRECTORY REPRODUCTION SCRIPT  " -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan

# Verify Prerequisites
if (!(Get-Command go -ErrorAction SilentlyContinue)) {
    Write-Host "INFRASTRUCTURE ERROR: Go is required but not found in PATH." -ForegroundColor Red
    exit 1
}
if (!(Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "INFRASTRUCTURE ERROR: Git is required but not found in PATH." -ForegroundColor Red
    exit 1
}

# Setup Artifact Directories
$Timestamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd_HHmmss")
$OutDir = "evidence\reproduction_$Timestamp"
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# Gather Runtime System Information
$GoVersion = (go version).Trim()
$OSInfo = [Environment]::OSVersion.VersionString
$GitCommit = if (Get-Command git -ErrorAction SilentlyContinue) { (git rev-parse HEAD 2>$null).Trim() } else { "Unknown" }
$GitBranch = if (Get-Command git -ErrorAction SilentlyContinue) { (git branch --show-current 2>$null).Trim() } else { "Unknown" }
if ([string]::IsNullOrWhiteSpace($GitCommit)) { $GitCommit = "Unknown" }
if ([string]::IsNullOrWhiteSpace($GitBranch)) { $GitBranch = "Unknown" }

Write-Host "
[SYSTEM CONTEXT]" -ForegroundColor DarkGray
Write-Host "OS: $OSInfo"
Write-Host "Go: $GoVersion"
Write-Host "Repository Path: $RepoRoot"
Write-Host "Git Commit: $GitCommit"
Write-Host "Git Branch: $GitBranch"

# Initialize Manifest
$Manifest = [ordered]@{
    run_id = $Timestamp
    timestamp_utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    repository = $RepoRoot
    git_commit = $GitCommit
    git_branch = $GitBranch
    go_version = $GoVersion
    os = $OSInfo
    mode = "Clean Local Reproduction"
    commands = @("go test -count=1 ./...", "go test -count=1 -v ./cmd -run TestDay10Benchmark")
    results = [ordered]@{
        core_tests = "PENDING"
        benchmark = "PENDING"
    }
    artifacts = @(
        "core_tests.log",
        "benchmark_run.log"
    )
}

$Failed = $false

# Execute Core Test Suite
Write-Host "
---> Running Core Security & Reproduction Tests..." -ForegroundColor Yellow
$CoreLog = "$OutDir\core_tests.log"
& go test -count=1 ./... 2>&1 | Tee-Object -FilePath $CoreLog
if ($LASTEXITCODE -eq 0) {
    Write-Host "PASS: Core Tests completed successfully." -ForegroundColor Green
    $Manifest.results.core_tests = "PASS"
} else {
    Write-Host "FAIL: Core Tests failed. Check $CoreLog for details." -ForegroundColor Red
    $Manifest.results.core_tests = "FAIL"
    $Failed = $true
}

# Execute Benchmark / Attack Lab Corpus
Write-Host "
---> Running Benchmark / Attack Lab..." -ForegroundColor Yellow
$BenchLog = "$OutDir\benchmark_run.log"
& go test -count=1 -v ./cmd -run TestDay10Benchmark 2>&1 | Tee-Object -FilePath $BenchLog
if ($LASTEXITCODE -eq 0) {
    Write-Host "PASS: Benchmark completed successfully." -ForegroundColor Green
    $Manifest.results.benchmark = "PASS"
} else {
    Write-Host "FAIL: Benchmark failed. Check $BenchLog for details." -ForegroundColor Red
    $Manifest.results.benchmark = "FAIL"
    $Failed = $true
}

# Finalize Artifacts
$Manifest | ConvertTo-Json -Depth 5 | Out-File "$OutDir\reproduction_manifest.json" -Encoding UTF8

Write-Host "
[SECURITY NOTICE] Evidence generated by this script on the creator's machine is classified as CREATOR-CONTROLLED. Independent validation requires execution by a third party in a separate clean environment." -ForegroundColor Magenta
Write-Host "
Artifacts saved to: .\$OutDir" -ForegroundColor Cyan

if ($Failed) {
    Write-Host "
REPRODUCTION RESULT: FAIL" -ForegroundColor Red
    exit 1
} else {
    Write-Host "
REPRODUCTION RESULT: PASS" -ForegroundColor Green
    exit 0
}
